packages:
  - apps/*
  - packages/*
catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.1
    "@types/react-dom": ^19.0.2
catalog:
  "@changesets/cli": ^2.27.10
  "@chromatic-com/storybook": ^3.2.2
  "@eslint/js": ^9.16.0
  "@hookform/resolvers": ^3.10.0
  "@next/eslint-plugin-next": ^15.0.4
  "@radix-ui/react-accordion": ^1.2.2
  "@radix-ui/react-alert-dialog": ^1.1.2
  "@radix-ui/react-aspect-ratio": ^1.1.1
  "@radix-ui/react-avatar": ^1.1.2
  "@radix-ui/react-checkbox": ^1.1.3
  "@radix-ui/react-collapsible": ^1.1.2
  "@radix-ui/react-context-menu": ^2.2.5
  "@radix-ui/react-dialog": ^1.1.4
  "@radix-ui/react-dropdown-menu": ^2.1.5
  "@radix-ui/react-hover-card": ^1.1.5
  "@radix-ui/react-label": 2.1.1
  "@radix-ui/react-menubar": ^1.1.5
  "@radix-ui/react-popover": ^1.1.4
  "@radix-ui/react-select": ^2.1.4
  "@radix-ui/react-slot": ^1.1.0
  "@radix-ui/react-switch": ^1.1.2
  "@storybook/addon-a11y": ^8.4.7
  "@storybook/addon-essentials": ^8.4.7
  "@storybook/addon-interactions": ^8.4.7
  "@storybook/addon-links": ^8.4.7
  "@storybook/addon-onboarding": ^8.4.7
  "@storybook/addon-themes": ^8.4.7
  "@storybook/blocks": ^8.4.7
  "@storybook/preview-api": ^8.4.7
  "@storybook/react": ^8.4.7
  "@storybook/react-vite": ^8.4.7
  "@storybook/test": ^8.4.7
  "@storybook/theming": ^8.4.7
  "@swc/core": ^1.10.1
  "@swc/jest": ^0.2.37
  "@testing-library/jest-dom": ^6.6.3
  "@testing-library/react": ^16.1.0
  "@testing-library/user-event": ^14.5.2
  "@types/jest": ^29.5.14
  "@types/node": ^22.10.5
  "@vitejs/plugin-react": ^4.3.4
  autoprefixer: ^10.4.20
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: 1.0.0
  date-fns: ^4.1.0
  embla-carousel-react: ^8.5.2
  eslint: ^9.16.0
  eslint-config-prettier: ^9.1.0
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.2
  eslint-plugin-react-hooks: ^5.1.0
  eslint-plugin-react-refresh: ^0.4.14
  eslint-plugin-simple-import-sort: ^12.1.1
  eslint-plugin-storybook: ^0.11.1
  eslint-plugin-turbo: ^2.3.3
  globals: ^15.13.0
  input-otp: ^1.4.2
  jest: ^29.7.0
  jest-environment-jsdom: ^29.7.0
  jest-matchmedia-mock: ^1.1.0
  lefthook: ^1.9.0
  lucide-react: ^0.468.0
  postcss: ^8.4.49
  prettier: ^3.4.2
  prettier-plugin-tailwindcss: ^0.6.9
  react-day-picker: 8.10.1
  react-hook-form: ^7.54.2
  recharts: ^2.15.0
  storybook: ^8.4.7
  storybook-dark-mode: ^4.0.2
  syncpack: ^13.0.0
  tailwind-merge: ^2.5.5
  tailwindcss: ^3.4.16
  tailwindcss-animate: ^1.0.7
  ts-node: ^10.9.2
  tsup: ^8.3.5
  tsx: ^4.19.2
  turbo: ^2.3.3
  typescript: ~5.6.2
  typescript-eslint: ^8.17.0
  vaul: ^1.1.2
  vite: ^6.0.1
  zod: ^3.24.1
